import type { Metadata } from "next";
import { Oxanium, Signika, Merienda } from "next/font/google";
import "../styles/globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { UserProvider } from "@/contexts/user_context";
import { CartProvider } from "@/contexts/cart_context";
import { Toaster } from "sonner";

const primaryFont = Oxanium({
  variable: "--font-primary",
  subsets: ["latin"],
});

const secondaryFont = Signika({
  variable: "--font-secondary",
  subsets: ["latin"],
});

const tertiaryFont = Merienda({
  variable: "--font-tertiary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FSM4FE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <CartProvider>
        <html lang="en">
          <body
            className={`${primaryFont.variable} ${secondaryFont.variable} ${tertiaryFont.variable} antialiased`}
          >
            <NavBar />
            <main>{children}</main>
            <Footer />
            <Toaster richColors position="top-center" theme="system" />
          </body>
        </html>
      </CartProvider>
    </UserProvider>
  );
}
